name: CI Checks

on:
  pull_request:
    branches: 
      - main
      - production
    paths:
      - 'src/app/**'

jobs:
  lint-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: cd src/app && bun install
      
      - name: Check i18n translations
        run: cd src/app && node scripts/check-i18n.js

      - name: Run linter
        run: cd src/app && bun lint

